apiVersion: v1
data:
  DAGSTER_HOME: /opt/dagster/dagster_home
  DAGSTER_K8S_PIPELINE_RUN_ENV_CONFIGMAP: mereo-dagster-pipeline-env
  DAGSTER_K8S_PIPELINE_RUN_IMAGE: docker.io/dagster/user-code-example:1.13.6
  DAGSTER_K8S_PIPELINE_RUN_IMAGE_PULL_POLICY: Always
  DAGSTER_K8S_PIPELINE_RUN_NAMESPACE: mereo-analytics
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: mereo-dagster
    meta.helm.sh/release-namespace: mereo-analytics
  labels:
    app: dagster
    app.kubernetes.io/managed-by: Helm
    chart: dagster-1.13.6
    heritage: Helm
    release: mereo-dagster
  name: mereo-dagster-pipeline-env
  namespace: mereo-analytics
