apiVersion: v1
data:
  postgresql-password: dGVzdA==
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: mereo-dagster
    meta.helm.sh/release-namespace: mereo-analytics
  labels:
    app: dagster
    app.kubernetes.io/managed-by: Helm
    chart: dagster-1.13.6
    heritage: Helm
    release: mereo-dagster
  name: dagster-postgresql-secret
  namespace: mereo-analytics
type: Opaque
