apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: mereo-dagster
    meta.helm.sh/release-namespace: mereo-analytics
  labels:
    app.kubernetes.io/instance: mereo-dagster
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dagster
    app.kubernetes.io/version: 1.13.6
    helm.sh/chart: dagster-1.13.6
  name: mereo-dagster
  namespace: mereo-analytics
